---
applicationName: "redHerring"
twitterAuth:
  consumerKey: "xnMNnEA01pv6evaSSPKPyA"
  consumerSecret: "A6IWkMn8muYEA5XAbA1AFe7ccKdBChjhpwkBpsodg"
  accessTokenKey: "1537962518-SWCbQJIUMwONBrT9En1jgcColVVJBr54sjjmdW6"
  accessTokenSecret: "wknX6wgmUocJnkjqzeboRZnmt7t3LF18C733bwZgW4"